// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/innovation-minning/pkg/db/ent/techniqueanalysis"
	"github.com/google/uuid"
)

// TechniqueAnalysisCreate is the builder for creating a TechniqueAnalysis entity.
type TechniqueAnalysisCreate struct {
	config
	mutation *TechniqueAnalysisMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAuthorID sets the "author_id" field.
func (tac *TechniqueAnalysisCreate) SetAuthorID(u uuid.UUID) *TechniqueAnalysisCreate {
	tac.mutation.SetAuthorID(u)
	return tac
}

// SetTitle sets the "title" field.
func (tac *TechniqueAnalysisCreate) SetTitle(s string) *TechniqueAnalysisCreate {
	tac.mutation.SetTitle(s)
	return tac
}

// SetContent sets the "content" field.
func (tac *TechniqueAnalysisCreate) SetContent(s string) *TechniqueAnalysisCreate {
	tac.mutation.SetContent(s)
	return tac
}

// SetAbstract sets the "abstract" field.
func (tac *TechniqueAnalysisCreate) SetAbstract(s string) *TechniqueAnalysisCreate {
	tac.mutation.SetAbstract(s)
	return tac
}

// SetProjectID sets the "project_id" field.
func (tac *TechniqueAnalysisCreate) SetProjectID(u uuid.UUID) *TechniqueAnalysisCreate {
	tac.mutation.SetProjectID(u)
	return tac
}

// SetCreateAt sets the "create_at" field.
func (tac *TechniqueAnalysisCreate) SetCreateAt(u uint32) *TechniqueAnalysisCreate {
	tac.mutation.SetCreateAt(u)
	return tac
}

// SetNillableCreateAt sets the "create_at" field if the given value is not nil.
func (tac *TechniqueAnalysisCreate) SetNillableCreateAt(u *uint32) *TechniqueAnalysisCreate {
	if u != nil {
		tac.SetCreateAt(*u)
	}
	return tac
}

// SetUpdateAt sets the "update_at" field.
func (tac *TechniqueAnalysisCreate) SetUpdateAt(u uint32) *TechniqueAnalysisCreate {
	tac.mutation.SetUpdateAt(u)
	return tac
}

// SetNillableUpdateAt sets the "update_at" field if the given value is not nil.
func (tac *TechniqueAnalysisCreate) SetNillableUpdateAt(u *uint32) *TechniqueAnalysisCreate {
	if u != nil {
		tac.SetUpdateAt(*u)
	}
	return tac
}

// SetDeleteAt sets the "delete_at" field.
func (tac *TechniqueAnalysisCreate) SetDeleteAt(u uint32) *TechniqueAnalysisCreate {
	tac.mutation.SetDeleteAt(u)
	return tac
}

// SetNillableDeleteAt sets the "delete_at" field if the given value is not nil.
func (tac *TechniqueAnalysisCreate) SetNillableDeleteAt(u *uint32) *TechniqueAnalysisCreate {
	if u != nil {
		tac.SetDeleteAt(*u)
	}
	return tac
}

// SetID sets the "id" field.
func (tac *TechniqueAnalysisCreate) SetID(u uuid.UUID) *TechniqueAnalysisCreate {
	tac.mutation.SetID(u)
	return tac
}

// Mutation returns the TechniqueAnalysisMutation object of the builder.
func (tac *TechniqueAnalysisCreate) Mutation() *TechniqueAnalysisMutation {
	return tac.mutation
}

// Save creates the TechniqueAnalysis in the database.
func (tac *TechniqueAnalysisCreate) Save(ctx context.Context) (*TechniqueAnalysis, error) {
	var (
		err  error
		node *TechniqueAnalysis
	)
	tac.defaults()
	if len(tac.hooks) == 0 {
		if err = tac.check(); err != nil {
			return nil, err
		}
		node, err = tac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TechniqueAnalysisMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tac.check(); err != nil {
				return nil, err
			}
			tac.mutation = mutation
			if node, err = tac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tac.hooks) - 1; i >= 0; i-- {
			if tac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tac *TechniqueAnalysisCreate) SaveX(ctx context.Context) *TechniqueAnalysis {
	v, err := tac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tac *TechniqueAnalysisCreate) Exec(ctx context.Context) error {
	_, err := tac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tac *TechniqueAnalysisCreate) ExecX(ctx context.Context) {
	if err := tac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tac *TechniqueAnalysisCreate) defaults() {
	if _, ok := tac.mutation.CreateAt(); !ok {
		v := techniqueanalysis.DefaultCreateAt()
		tac.mutation.SetCreateAt(v)
	}
	if _, ok := tac.mutation.UpdateAt(); !ok {
		v := techniqueanalysis.DefaultUpdateAt()
		tac.mutation.SetUpdateAt(v)
	}
	if _, ok := tac.mutation.DeleteAt(); !ok {
		v := techniqueanalysis.DefaultDeleteAt()
		tac.mutation.SetDeleteAt(v)
	}
	if _, ok := tac.mutation.ID(); !ok {
		v := techniqueanalysis.DefaultID()
		tac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tac *TechniqueAnalysisCreate) check() error {
	if _, ok := tac.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "author_id"`)}
	}
	if _, ok := tac.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "title"`)}
	}
	if _, ok := tac.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "content"`)}
	}
	if _, ok := tac.mutation.Abstract(); !ok {
		return &ValidationError{Name: "abstract", err: errors.New(`ent: missing required field "abstract"`)}
	}
	if _, ok := tac.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "project_id"`)}
	}
	if _, ok := tac.mutation.CreateAt(); !ok {
		return &ValidationError{Name: "create_at", err: errors.New(`ent: missing required field "create_at"`)}
	}
	if _, ok := tac.mutation.UpdateAt(); !ok {
		return &ValidationError{Name: "update_at", err: errors.New(`ent: missing required field "update_at"`)}
	}
	if _, ok := tac.mutation.DeleteAt(); !ok {
		return &ValidationError{Name: "delete_at", err: errors.New(`ent: missing required field "delete_at"`)}
	}
	return nil
}

func (tac *TechniqueAnalysisCreate) sqlSave(ctx context.Context) (*TechniqueAnalysis, error) {
	_node, _spec := tac.createSpec()
	if err := sqlgraph.CreateNode(ctx, tac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		_node.ID = _spec.ID.Value.(uuid.UUID)
	}
	return _node, nil
}

func (tac *TechniqueAnalysisCreate) createSpec() (*TechniqueAnalysis, *sqlgraph.CreateSpec) {
	var (
		_node = &TechniqueAnalysis{config: tac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: techniqueanalysis.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: techniqueanalysis.FieldID,
			},
		}
	)
	_spec.OnConflict = tac.conflict
	if id, ok := tac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tac.mutation.AuthorID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: techniqueanalysis.FieldAuthorID,
		})
		_node.AuthorID = value
	}
	if value, ok := tac.mutation.Title(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: techniqueanalysis.FieldTitle,
		})
		_node.Title = value
	}
	if value, ok := tac.mutation.Content(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: techniqueanalysis.FieldContent,
		})
		_node.Content = value
	}
	if value, ok := tac.mutation.Abstract(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: techniqueanalysis.FieldAbstract,
		})
		_node.Abstract = value
	}
	if value, ok := tac.mutation.ProjectID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: techniqueanalysis.FieldProjectID,
		})
		_node.ProjectID = value
	}
	if value, ok := tac.mutation.CreateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: techniqueanalysis.FieldCreateAt,
		})
		_node.CreateAt = value
	}
	if value, ok := tac.mutation.UpdateAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: techniqueanalysis.FieldUpdateAt,
		})
		_node.UpdateAt = value
	}
	if value, ok := tac.mutation.DeleteAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: techniqueanalysis.FieldDeleteAt,
		})
		_node.DeleteAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TechniqueAnalysis.Create().
//		SetAuthorID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TechniqueAnalysisUpsert) {
//			SetAuthorID(v+v).
//		}).
//		Exec(ctx)
//
func (tac *TechniqueAnalysisCreate) OnConflict(opts ...sql.ConflictOption) *TechniqueAnalysisUpsertOne {
	tac.conflict = opts
	return &TechniqueAnalysisUpsertOne{
		create: tac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TechniqueAnalysis.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tac *TechniqueAnalysisCreate) OnConflictColumns(columns ...string) *TechniqueAnalysisUpsertOne {
	tac.conflict = append(tac.conflict, sql.ConflictColumns(columns...))
	return &TechniqueAnalysisUpsertOne{
		create: tac,
	}
}

type (
	// TechniqueAnalysisUpsertOne is the builder for "upsert"-ing
	//  one TechniqueAnalysis node.
	TechniqueAnalysisUpsertOne struct {
		create *TechniqueAnalysisCreate
	}

	// TechniqueAnalysisUpsert is the "OnConflict" setter.
	TechniqueAnalysisUpsert struct {
		*sql.UpdateSet
	}
)

// SetAuthorID sets the "author_id" field.
func (u *TechniqueAnalysisUpsert) SetAuthorID(v uuid.UUID) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldAuthorID, v)
	return u
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateAuthorID() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldAuthorID)
	return u
}

// SetTitle sets the "title" field.
func (u *TechniqueAnalysisUpsert) SetTitle(v string) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateTitle() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *TechniqueAnalysisUpsert) SetContent(v string) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateContent() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldContent)
	return u
}

// SetAbstract sets the "abstract" field.
func (u *TechniqueAnalysisUpsert) SetAbstract(v string) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldAbstract, v)
	return u
}

// UpdateAbstract sets the "abstract" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateAbstract() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldAbstract)
	return u
}

// SetProjectID sets the "project_id" field.
func (u *TechniqueAnalysisUpsert) SetProjectID(v uuid.UUID) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldProjectID, v)
	return u
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateProjectID() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldProjectID)
	return u
}

// SetCreateAt sets the "create_at" field.
func (u *TechniqueAnalysisUpsert) SetCreateAt(v uint32) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldCreateAt, v)
	return u
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateCreateAt() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldCreateAt)
	return u
}

// SetUpdateAt sets the "update_at" field.
func (u *TechniqueAnalysisUpsert) SetUpdateAt(v uint32) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldUpdateAt, v)
	return u
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateUpdateAt() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldUpdateAt)
	return u
}

// SetDeleteAt sets the "delete_at" field.
func (u *TechniqueAnalysisUpsert) SetDeleteAt(v uint32) *TechniqueAnalysisUpsert {
	u.Set(techniqueanalysis.FieldDeleteAt, v)
	return u
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsert) UpdateDeleteAt() *TechniqueAnalysisUpsert {
	u.SetExcluded(techniqueanalysis.FieldDeleteAt)
	return u
}

// UpdateNewValues updates the fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TechniqueAnalysis.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(techniqueanalysis.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *TechniqueAnalysisUpsertOne) UpdateNewValues() *TechniqueAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(techniqueanalysis.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.TechniqueAnalysis.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *TechniqueAnalysisUpsertOne) Ignore() *TechniqueAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TechniqueAnalysisUpsertOne) DoNothing() *TechniqueAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TechniqueAnalysisCreate.OnConflict
// documentation for more info.
func (u *TechniqueAnalysisUpsertOne) Update(set func(*TechniqueAnalysisUpsert)) *TechniqueAnalysisUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TechniqueAnalysisUpsert{UpdateSet: update})
	}))
	return u
}

// SetAuthorID sets the "author_id" field.
func (u *TechniqueAnalysisUpsertOne) SetAuthorID(v uuid.UUID) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateAuthorID() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateAuthorID()
	})
}

// SetTitle sets the "title" field.
func (u *TechniqueAnalysisUpsertOne) SetTitle(v string) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateTitle() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *TechniqueAnalysisUpsertOne) SetContent(v string) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateContent() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateContent()
	})
}

// SetAbstract sets the "abstract" field.
func (u *TechniqueAnalysisUpsertOne) SetAbstract(v string) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetAbstract(v)
	})
}

// UpdateAbstract sets the "abstract" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateAbstract() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateAbstract()
	})
}

// SetProjectID sets the "project_id" field.
func (u *TechniqueAnalysisUpsertOne) SetProjectID(v uuid.UUID) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateProjectID() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateProjectID()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *TechniqueAnalysisUpsertOne) SetCreateAt(v uint32) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateCreateAt() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *TechniqueAnalysisUpsertOne) SetUpdateAt(v uint32) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateUpdateAt() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *TechniqueAnalysisUpsertOne) SetDeleteAt(v uint32) *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertOne) UpdateDeleteAt() *TechniqueAnalysisUpsertOne {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateDeleteAt()
	})
}

// Exec executes the query.
func (u *TechniqueAnalysisUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TechniqueAnalysisCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TechniqueAnalysisUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TechniqueAnalysisUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TechniqueAnalysisUpsertOne.ID is not supported by MySQL driver. Use TechniqueAnalysisUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TechniqueAnalysisUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TechniqueAnalysisCreateBulk is the builder for creating many TechniqueAnalysis entities in bulk.
type TechniqueAnalysisCreateBulk struct {
	config
	builders []*TechniqueAnalysisCreate
	conflict []sql.ConflictOption
}

// Save creates the TechniqueAnalysis entities in the database.
func (tacb *TechniqueAnalysisCreateBulk) Save(ctx context.Context) ([]*TechniqueAnalysis, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tacb.builders))
	nodes := make([]*TechniqueAnalysis, len(tacb.builders))
	mutators := make([]Mutator, len(tacb.builders))
	for i := range tacb.builders {
		func(i int, root context.Context) {
			builder := tacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TechniqueAnalysisMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tacb *TechniqueAnalysisCreateBulk) SaveX(ctx context.Context) []*TechniqueAnalysis {
	v, err := tacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tacb *TechniqueAnalysisCreateBulk) Exec(ctx context.Context) error {
	_, err := tacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tacb *TechniqueAnalysisCreateBulk) ExecX(ctx context.Context) {
	if err := tacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TechniqueAnalysis.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TechniqueAnalysisUpsert) {
//			SetAuthorID(v+v).
//		}).
//		Exec(ctx)
//
func (tacb *TechniqueAnalysisCreateBulk) OnConflict(opts ...sql.ConflictOption) *TechniqueAnalysisUpsertBulk {
	tacb.conflict = opts
	return &TechniqueAnalysisUpsertBulk{
		create: tacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TechniqueAnalysis.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tacb *TechniqueAnalysisCreateBulk) OnConflictColumns(columns ...string) *TechniqueAnalysisUpsertBulk {
	tacb.conflict = append(tacb.conflict, sql.ConflictColumns(columns...))
	return &TechniqueAnalysisUpsertBulk{
		create: tacb,
	}
}

// TechniqueAnalysisUpsertBulk is the builder for "upsert"-ing
// a bulk of TechniqueAnalysis nodes.
type TechniqueAnalysisUpsertBulk struct {
	create *TechniqueAnalysisCreateBulk
}

// UpdateNewValues updates the fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TechniqueAnalysis.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(techniqueanalysis.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *TechniqueAnalysisUpsertBulk) UpdateNewValues() *TechniqueAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(techniqueanalysis.FieldID)
				return
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TechniqueAnalysis.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *TechniqueAnalysisUpsertBulk) Ignore() *TechniqueAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TechniqueAnalysisUpsertBulk) DoNothing() *TechniqueAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TechniqueAnalysisCreateBulk.OnConflict
// documentation for more info.
func (u *TechniqueAnalysisUpsertBulk) Update(set func(*TechniqueAnalysisUpsert)) *TechniqueAnalysisUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TechniqueAnalysisUpsert{UpdateSet: update})
	}))
	return u
}

// SetAuthorID sets the "author_id" field.
func (u *TechniqueAnalysisUpsertBulk) SetAuthorID(v uuid.UUID) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetAuthorID(v)
	})
}

// UpdateAuthorID sets the "author_id" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateAuthorID() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateAuthorID()
	})
}

// SetTitle sets the "title" field.
func (u *TechniqueAnalysisUpsertBulk) SetTitle(v string) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateTitle() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateTitle()
	})
}

// SetContent sets the "content" field.
func (u *TechniqueAnalysisUpsertBulk) SetContent(v string) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateContent() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateContent()
	})
}

// SetAbstract sets the "abstract" field.
func (u *TechniqueAnalysisUpsertBulk) SetAbstract(v string) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetAbstract(v)
	})
}

// UpdateAbstract sets the "abstract" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateAbstract() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateAbstract()
	})
}

// SetProjectID sets the "project_id" field.
func (u *TechniqueAnalysisUpsertBulk) SetProjectID(v uuid.UUID) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetProjectID(v)
	})
}

// UpdateProjectID sets the "project_id" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateProjectID() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateProjectID()
	})
}

// SetCreateAt sets the "create_at" field.
func (u *TechniqueAnalysisUpsertBulk) SetCreateAt(v uint32) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetCreateAt(v)
	})
}

// UpdateCreateAt sets the "create_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateCreateAt() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateCreateAt()
	})
}

// SetUpdateAt sets the "update_at" field.
func (u *TechniqueAnalysisUpsertBulk) SetUpdateAt(v uint32) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetUpdateAt(v)
	})
}

// UpdateUpdateAt sets the "update_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateUpdateAt() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateUpdateAt()
	})
}

// SetDeleteAt sets the "delete_at" field.
func (u *TechniqueAnalysisUpsertBulk) SetDeleteAt(v uint32) *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.SetDeleteAt(v)
	})
}

// UpdateDeleteAt sets the "delete_at" field to the value that was provided on create.
func (u *TechniqueAnalysisUpsertBulk) UpdateDeleteAt() *TechniqueAnalysisUpsertBulk {
	return u.Update(func(s *TechniqueAnalysisUpsert) {
		s.UpdateDeleteAt()
	})
}

// Exec executes the query.
func (u *TechniqueAnalysisUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TechniqueAnalysisCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TechniqueAnalysisCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TechniqueAnalysisUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
