// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/innovation-minning/pkg/db/ent/predicate"
	"github.com/NpoolPlatform/innovation-minning/pkg/db/ent/trendanalysis"
	"github.com/google/uuid"
)

// TrendAnalysisQuery is the builder for querying TrendAnalysis entities.
type TrendAnalysisQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TrendAnalysis
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrendAnalysisQuery builder.
func (taq *TrendAnalysisQuery) Where(ps ...predicate.TrendAnalysis) *TrendAnalysisQuery {
	taq.predicates = append(taq.predicates, ps...)
	return taq
}

// Limit adds a limit step to the query.
func (taq *TrendAnalysisQuery) Limit(limit int) *TrendAnalysisQuery {
	taq.limit = &limit
	return taq
}

// Offset adds an offset step to the query.
func (taq *TrendAnalysisQuery) Offset(offset int) *TrendAnalysisQuery {
	taq.offset = &offset
	return taq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (taq *TrendAnalysisQuery) Unique(unique bool) *TrendAnalysisQuery {
	taq.unique = &unique
	return taq
}

// Order adds an order step to the query.
func (taq *TrendAnalysisQuery) Order(o ...OrderFunc) *TrendAnalysisQuery {
	taq.order = append(taq.order, o...)
	return taq
}

// First returns the first TrendAnalysis entity from the query.
// Returns a *NotFoundError when no TrendAnalysis was found.
func (taq *TrendAnalysisQuery) First(ctx context.Context) (*TrendAnalysis, error) {
	nodes, err := taq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{trendanalysis.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (taq *TrendAnalysisQuery) FirstX(ctx context.Context) *TrendAnalysis {
	node, err := taq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TrendAnalysis ID from the query.
// Returns a *NotFoundError when no TrendAnalysis ID was found.
func (taq *TrendAnalysisQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = taq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{trendanalysis.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (taq *TrendAnalysisQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := taq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TrendAnalysis entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one TrendAnalysis entity is not found.
// Returns a *NotFoundError when no TrendAnalysis entities are found.
func (taq *TrendAnalysisQuery) Only(ctx context.Context) (*TrendAnalysis, error) {
	nodes, err := taq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{trendanalysis.Label}
	default:
		return nil, &NotSingularError{trendanalysis.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (taq *TrendAnalysisQuery) OnlyX(ctx context.Context) *TrendAnalysis {
	node, err := taq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TrendAnalysis ID in the query.
// Returns a *NotSingularError when exactly one TrendAnalysis ID is not found.
// Returns a *NotFoundError when no entities are found.
func (taq *TrendAnalysisQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = taq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = &NotSingularError{trendanalysis.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (taq *TrendAnalysisQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := taq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TrendAnalyses.
func (taq *TrendAnalysisQuery) All(ctx context.Context) ([]*TrendAnalysis, error) {
	if err := taq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return taq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (taq *TrendAnalysisQuery) AllX(ctx context.Context) []*TrendAnalysis {
	nodes, err := taq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TrendAnalysis IDs.
func (taq *TrendAnalysisQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := taq.Select(trendanalysis.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (taq *TrendAnalysisQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := taq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (taq *TrendAnalysisQuery) Count(ctx context.Context) (int, error) {
	if err := taq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return taq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (taq *TrendAnalysisQuery) CountX(ctx context.Context) int {
	count, err := taq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (taq *TrendAnalysisQuery) Exist(ctx context.Context) (bool, error) {
	if err := taq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return taq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (taq *TrendAnalysisQuery) ExistX(ctx context.Context) bool {
	exist, err := taq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrendAnalysisQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (taq *TrendAnalysisQuery) Clone() *TrendAnalysisQuery {
	if taq == nil {
		return nil
	}
	return &TrendAnalysisQuery{
		config:     taq.config,
		limit:      taq.limit,
		offset:     taq.offset,
		order:      append([]OrderFunc{}, taq.order...),
		predicates: append([]predicate.TrendAnalysis{}, taq.predicates...),
		// clone intermediate query.
		sql:  taq.sql.Clone(),
		path: taq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TrendAnalysis.Query().
//		GroupBy(trendanalysis.FieldProjectID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (taq *TrendAnalysisQuery) GroupBy(field string, fields ...string) *TrendAnalysisGroupBy {
	group := &TrendAnalysisGroupBy{config: taq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := taq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return taq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProjectID uuid.UUID `json:"project_id,omitempty"`
//	}
//
//	client.TrendAnalysis.Query().
//		Select(trendanalysis.FieldProjectID).
//		Scan(ctx, &v)
//
func (taq *TrendAnalysisQuery) Select(fields ...string) *TrendAnalysisSelect {
	taq.fields = append(taq.fields, fields...)
	return &TrendAnalysisSelect{TrendAnalysisQuery: taq}
}

func (taq *TrendAnalysisQuery) prepareQuery(ctx context.Context) error {
	for _, f := range taq.fields {
		if !trendanalysis.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if taq.path != nil {
		prev, err := taq.path(ctx)
		if err != nil {
			return err
		}
		taq.sql = prev
	}
	return nil
}

func (taq *TrendAnalysisQuery) sqlAll(ctx context.Context) ([]*TrendAnalysis, error) {
	var (
		nodes = []*TrendAnalysis{}
		_spec = taq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TrendAnalysis{config: taq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, taq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (taq *TrendAnalysisQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := taq.querySpec()
	return sqlgraph.CountNodes(ctx, taq.driver, _spec)
}

func (taq *TrendAnalysisQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := taq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (taq *TrendAnalysisQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   trendanalysis.Table,
			Columns: trendanalysis.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: trendanalysis.FieldID,
			},
		},
		From:   taq.sql,
		Unique: true,
	}
	if unique := taq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := taq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, trendanalysis.FieldID)
		for i := range fields {
			if fields[i] != trendanalysis.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := taq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := taq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := taq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := taq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (taq *TrendAnalysisQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(taq.driver.Dialect())
	t1 := builder.Table(trendanalysis.Table)
	columns := taq.fields
	if len(columns) == 0 {
		columns = trendanalysis.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if taq.sql != nil {
		selector = taq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range taq.predicates {
		p(selector)
	}
	for _, p := range taq.order {
		p(selector)
	}
	if offset := taq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := taq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrendAnalysisGroupBy is the group-by builder for TrendAnalysis entities.
type TrendAnalysisGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tagb *TrendAnalysisGroupBy) Aggregate(fns ...AggregateFunc) *TrendAnalysisGroupBy {
	tagb.fns = append(tagb.fns, fns...)
	return tagb
}

// Scan applies the group-by query and scans the result into the given value.
func (tagb *TrendAnalysisGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tagb.path(ctx)
	if err != nil {
		return err
	}
	tagb.sql = query
	return tagb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tagb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) StringsX(ctx context.Context) []string {
	v, err := tagb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tagb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) StringX(ctx context.Context) string {
	v, err := tagb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) IntsX(ctx context.Context) []int {
	v, err := tagb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tagb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) IntX(ctx context.Context) int {
	v, err := tagb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tagb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tagb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tagb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tagb.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tagb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tagb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tagb *TrendAnalysisGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tagb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tagb *TrendAnalysisGroupBy) BoolX(ctx context.Context) bool {
	v, err := tagb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tagb *TrendAnalysisGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tagb.fields {
		if !trendanalysis.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tagb *TrendAnalysisGroupBy) sqlQuery() *sql.Selector {
	selector := tagb.sql.Select()
	aggregation := make([]string, 0, len(tagb.fns))
	for _, fn := range tagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tagb.fields)+len(tagb.fns))
		for _, f := range tagb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tagb.fields...)...)
}

// TrendAnalysisSelect is the builder for selecting fields of TrendAnalysis entities.
type TrendAnalysisSelect struct {
	*TrendAnalysisQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tas *TrendAnalysisSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tas.prepareQuery(ctx); err != nil {
		return err
	}
	tas.sql = tas.TrendAnalysisQuery.sqlQuery(ctx)
	return tas.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tas *TrendAnalysisSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tas.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tas *TrendAnalysisSelect) StringsX(ctx context.Context) []string {
	v, err := tas.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tas.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tas *TrendAnalysisSelect) StringX(ctx context.Context) string {
	v, err := tas.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tas *TrendAnalysisSelect) IntsX(ctx context.Context) []int {
	v, err := tas.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tas.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tas *TrendAnalysisSelect) IntX(ctx context.Context) int {
	v, err := tas.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tas *TrendAnalysisSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tas.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tas.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tas *TrendAnalysisSelect) Float64X(ctx context.Context) float64 {
	v, err := tas.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tas.fields) > 1 {
		return nil, errors.New("ent: TrendAnalysisSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tas.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tas *TrendAnalysisSelect) BoolsX(ctx context.Context) []bool {
	v, err := tas.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tas *TrendAnalysisSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tas.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{trendanalysis.Label}
	default:
		err = fmt.Errorf("ent: TrendAnalysisSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tas *TrendAnalysisSelect) BoolX(ctx context.Context) bool {
	v, err := tas.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tas *TrendAnalysisSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tas.sql.Query()
	if err := tas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
